Transaction Costs Optimization
Marigold/universal-portfolios pull request #46
Opened 2021-06-08 17:43 UTC by DrPaprikaa

First interpretation of the TCO framework
from this paper : https://ink.library.smu.edu.sg/cgi/viewcontent.cgi?referer=&httpsredir=1&article=4761&context=sis_research

Should update_olmar() still be used ? Isn't TCO ad add-on to olmar and other framworks, in which case update_tco() should be located in Algo ?
I've chosen to test it in this file but you know your repo better than me, feel free to make the necessary adjustments.
DrPaprika

2021-06-09 13:29 UTC, Marigold requested changes
Looks good! Requested one minor change. Have you tried it on some real data? Does it give reasonable results?

2021-06-09 13:29 UTC, Marigold commented on universal/algos/olmar.py
> +        trx_fee_pct = 0.1
Could you add this to `__init__` as parameter? You can then reference it with `self.trx_fee_pct` here. Also please only run `update_tco` if `trx_fee_pct` is not `None` (which should be probably default value)

2021-06-09 13:34 UTC, Marigold commented
> Should update_olmar() still be used ? Isn't TCO an add-on to olmar and other framworks, in which case update_tco() should be located in Algo?

Hmm, good question. I wouldn't personally complicate it at this point and keep it only here, but if find yourself using it for other algos as well, then you can implement it after this line https://github.com/Marigold/universal-portfolios/blob/master/universal/algo.py#L96 and make transaction cost optimization a parameter in `__init__` (probably by passing kwargs to `Algo.__init__` through `super()`. Let me know if I'm not clear and you want to implement this)

2021-06-09 14:18 UTC, DrPaprikaa commented
Thanks for the review. I moved `update_tco()` in `Algo` in another PR (didn't know how to add changes to another file in the current PR).
TCO is called in `Algo` only when `trx_fee_pct` > 0, and `trx_fee_pct` defaults to 0.
If we go this route, then `**kwargs` need to be passed to all suitable algos in the algos folder to that they can benefit from TCO.
My tests on real data do not yield significant benefits compared to existing models, on the contrary of what the paper says. I would be glad to have your opinion on this !

2021-06-10 16:04 UTC, Marigold commented
> My tests on real data do not yield significant benefits compared to existing models, on the contrary of what the paper says. I would be glad to have your opinion on this !

Haha, yeah, research papers... they're very often far from reality and done on cherry-picked datasets if you ask me. Still, the ideas are sound.

2021-06-10 16:09 UTC, Marigold commented
Btw should we close this in favor of https://github.com/Marigold/universal-portfolios/pull/47?

2021-06-10 16:35 UTC, DrPaprikaa commented
We can close this :) Could you please add `**kwargs` to the algos in `universal.algos` ?

2021-06-15 10:06 UTC, closed without merging